"""Add_Esta_Pagado

Revision ID: 3ad7345092a4
Revises: aa9cf64ec530
Create Date: 2026-07-20 22:36:53.818041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ad7345092a4'
down_revision = 'aa9cf64ec530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('division_gastos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('esta_pagado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('division_gastos', schema=None) as batch_op:
        batch_op.drop_column('esta_pagado')

    # ### end Alembic commands ###
