"""Add color to EventoLogistico and SuscripcionDeporte

Revision ID: 573ce00e84e7
Revises: d2ff2a15a1ba
Create Date: 2026-08-22 14:32:01.918791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573ce00e84e7'
down_revision = 'd2ff2a15a1ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos_logisticos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=20), nullable=True))

    with op.batch_alter_table('suscripciones_deporte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suscripciones_deporte', schema=None) as batch_op:
        batch_op.drop_column('color')

    with op.batch_alter_table('eventos_logisticos', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
