"""Added notifications preferences

Revision ID: 7a10ab1fb344
Revises: c9d97714ae0b
Create Date: 2026-08-16 11:25:39.292722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a10ab1fb344'
down_revision = 'c9d97714ae0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_global',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_principal_telegram_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eventos_logisticos', schema=None) as batch_op:
        batch_op.alter_column('frecuencia',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'none'::character varying"))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recibir_resumen_matutino', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recibir_alertas_vencimiento', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recibir_recordatorios_tareas', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('recibir_recordatorios_tareas')
        batch_op.drop_column('recibir_alertas_vencimiento')
        batch_op.drop_column('recibir_resumen_matutino')

    with op.batch_alter_table('eventos_logisticos', schema=None) as batch_op:
        batch_op.alter_column('frecuencia',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'none'::character varying"))

    op.drop_table('configuracion_global')
    # ### end Alembic commands ###
