"""Añadir codigo y password a Casa

Revision ID: 9e5f322073e5
Revises: c8851bedb7ad
Create Date: 2026-08-25 21:02:36.199215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e5f322073e5'
down_revision = 'c8851bedb7ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('casas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_invitacion', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_casas_codigo_invitacion'), ['codigo_invitacion'], unique=True)

    with op.batch_alter_table('comercios', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('configuracion_global', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('detalle_gastos', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('division_gastos', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('eventos_logisticos', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('historial_tareas', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('horario_comidas', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('ingrediente_receta', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('menu_semanal', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('metas_ahorro', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('modelo_tareas', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('recetas', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('salas', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('salto_tareas', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('sub_ubicaciones', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('suscripciones_deporte', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('ubicaciones', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ubicaciones', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('suscripciones_deporte', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('sub_ubicaciones', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('salto_tareas', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('salas', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('recetas', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('modelo_tareas', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('metas_ahorro', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('menu_semanal', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('ingrediente_receta', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('horario_comidas', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('historial_tareas', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('eventos_logisticos', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('division_gastos', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('detalle_gastos', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('configuracion_global', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('comercios', schema=None) as batch_op:
        batch_op.alter_column('casa_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('casas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_casas_codigo_invitacion'))
        batch_op.drop_column('password_hash')
        batch_op.drop_column('codigo_invitacion')

    # ### end Alembic commands ###
