"""Add hora_alerta_stock

Revision ID: b11d49e82f6c
Revises: 7a10ab1fb344
Create Date: 2026-08-20 20:51:27.230738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b11d49e82f6c'
down_revision = '7a10ab1fb344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracion_global', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hora_alerta_stock', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracion_global', schema=None) as batch_op:
        batch_op.drop_column('hora_alerta_stock')

    # ### end Alembic commands ###
