"""Add multi_tenant

Revision ID: c8851bedb7ad
Revises: 573ce00e84e7
Create Date: 2026-08-25 17:45:49.001126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8851bedb7ad'
down_revision = '573ce00e84e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # --- Custom Downgrade RLS ---
    tables = [
        'comercios', 'configuracion_global', 'detalle_gastos', 'division_gastos', 
        'gastos', 'historial_tareas', 'horario_comidas', 
        'ingrediente_receta', 'menu_semanal', 'metas_ahorro', 'modelo_tareas', 
        'movimientos', 'productos', 'recetas', 'salas', 'salto_tareas', 
        'sub_ubicaciones', 'suscripciones_deporte', 'tareas', 'ubicaciones'
    ]
    for table in tables:
        op.execute(f"DROP POLICY IF EXISTS aislar_casa ON {table};")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;")
    # --- End Custom Downgrade ---

    op.create_table('casas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_casa',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('casa_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=True),
    sa.Column('estado_invitacion', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['casa_id'], ['casas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'casa_id')
    )
    with op.batch_alter_table('comercios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('casa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'casas', ['casa_id'], ['id'])

    with op.batch_alter_table('configuracion_global', schema=None) as batch_op:
        batch_op.add_column(sa.Column('casa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'casas', ['casa_id'], ['id'])

    with op.batch_alter_table('detalle_gastos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('casa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'casas', ['casa_id'], ['id'])

    with op.batch_alter_table('division_gastos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('casa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'casas', ['casa_id'], ['id'])

    with op.batch_alter_table('eventos_logisticos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('casa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'casas', ['casa_id'], ['id'])

    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('casa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'casas', ['casa_id'], ['id'])

    with op.batch_alter_table('historial_tareas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('casa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'casas', ['casa_id'], ['id'])

    with op.batch_alter_table('horario_comidas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('casa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'casas', ['casa_id'], ['id'])

    with op.batch_alter_table('ingrediente_receta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('casa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'casas', ['casa_id'], ['id'])

    with op.batch_alter_table('menu_semanal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('casa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'casas', ['casa_id'], ['id'])

    with op.batch_alter_table('metas_ahorro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('casa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'casas', ['casa_id'], ['id'])

    with op.batch_alter_table('modelo_tareas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('casa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'casas', ['casa_id'], ['id'])

    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('casa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'casas', ['casa_id'], ['id'])

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('casa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'casas', ['casa_id'], ['id'])

    with op.batch_alter_table('recetas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('casa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'casas', ['casa_id'], ['id'])

    with op.batch_alter_table('salas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('casa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'casas', ['casa_id'], ['id'])

    with op.batch_alter_table('salto_tareas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('casa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'casas', ['casa_id'], ['id'])

    with op.batch_alter_table('sub_ubicaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('casa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'casas', ['casa_id'], ['id'])

    with op.batch_alter_table('suscripciones_deporte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('casa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'casas', ['casa_id'], ['id'])

    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('casa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'casas', ['casa_id'], ['id'])

    with op.batch_alter_table('ubicaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('casa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'casas', ['casa_id'], ['id'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('casa_activa_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'casas', ['casa_activa_id'], ['id'])


    # --- Custom Multi-Tenant Data Migration ---
    # 1. Crear Casa Default
    op.execute("INSERT INTO casas (nombre, fecha_creacion) VALUES ('Casa Principal', NOW()) ON CONFLICT DO NOTHING")
    
    # 2. Asociar todos los usuarios a la casa por default
    op.execute('''
        INSERT INTO usuario_casa (usuario_id, casa_id, rol, estado_invitacion)
        SELECT id, (SELECT id FROM casas ORDER BY id ASC LIMIT 1), 'admin', 'aceptada' FROM usuarios
        ON CONFLICT DO NOTHING
    ''')

    # 3. Asignar casa activa
    op.execute("UPDATE usuarios SET casa_activa_id = (SELECT id FROM casas ORDER BY id ASC LIMIT 1) WHERE casa_activa_id IS NULL")

    # 4. Actualizar todos los casa_id en las tablas
    tables = [
        'comercios', 'configuracion_global', 'detalle_gastos', 'division_gastos', 
        'eventos_logisticos', 'gastos', 'historial_tareas', 'horario_comidas', 
        'ingrediente_receta', 'menu_semanal', 'metas_ahorro', 'modelo_tareas', 
        'movimientos', 'productos', 'recetas', 'salas', 'salto_tareas', 
        'sub_ubicaciones', 'suscripciones_deporte', 'tareas', 'ubicaciones'
    ]
    for table in tables:
        op.execute(f"UPDATE {table} SET casa_id = (SELECT id FROM casas ORDER BY id ASC LIMIT 1) WHERE casa_id IS NULL")
        # Hacer la columna NOT NULL
        op.execute(f"ALTER TABLE {table} ALTER COLUMN casa_id SET NOT NULL")

    # 5. Aplicar RLS a todas menos eventos_logisticos
    for table in tables:
        if table != 'eventos_logisticos':
            op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
            op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY;")
            op.execute(f"CREATE POLICY aislar_casa ON {table} USING (casa_id = NULLIF(current_setting('app.current_casa_id', TRUE), '')::integer);")
    
    # --- End Custom Migration ---

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # --- Custom Downgrade RLS ---
    tables = [
        'comercios', 'configuracion_global', 'detalle_gastos', 'division_gastos', 
        'gastos', 'historial_tareas', 'horario_comidas', 
        'ingrediente_receta', 'menu_semanal', 'metas_ahorro', 'modelo_tareas', 
        'movimientos', 'productos', 'recetas', 'salas', 'salto_tareas', 
        'sub_ubicaciones', 'suscripciones_deporte', 'tareas', 'ubicaciones'
    ]
    for table in tables:
        op.execute(f"DROP POLICY IF EXISTS aislar_casa ON {table};")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;")
    # --- End Custom Downgrade ---

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('casa_activa_id')

    with op.batch_alter_table('ubicaciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('casa_id')

    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('casa_id')

    with op.batch_alter_table('suscripciones_deporte', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('casa_id')

    with op.batch_alter_table('sub_ubicaciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('casa_id')

    with op.batch_alter_table('salto_tareas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('casa_id')

    with op.batch_alter_table('salas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('casa_id')

    with op.batch_alter_table('recetas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('casa_id')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('casa_id')

    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('casa_id')

    with op.batch_alter_table('modelo_tareas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('casa_id')

    with op.batch_alter_table('metas_ahorro', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('casa_id')

    with op.batch_alter_table('menu_semanal', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('casa_id')

    with op.batch_alter_table('ingrediente_receta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('casa_id')

    with op.batch_alter_table('horario_comidas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('casa_id')

    with op.batch_alter_table('historial_tareas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('casa_id')

    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('casa_id')

    with op.batch_alter_table('eventos_logisticos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('casa_id')

    with op.batch_alter_table('division_gastos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('casa_id')

    with op.batch_alter_table('detalle_gastos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('casa_id')

    with op.batch_alter_table('configuracion_global', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('casa_id')

    with op.batch_alter_table('comercios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('casa_id')

    op.drop_table('usuario_casa')
    op.drop_table('casas')

    # --- Custom Multi-Tenant Data Migration ---
    # 1. Crear Casa Default
    op.execute("INSERT INTO casas (nombre, fecha_creacion) VALUES ('Casa Principal', NOW()) ON CONFLICT DO NOTHING")
    
    # 2. Asociar todos los usuarios a la casa por default
    op.execute('''
        INSERT INTO usuario_casa (usuario_id, casa_id, rol, estado_invitacion)
        SELECT id, (SELECT id FROM casas ORDER BY id ASC LIMIT 1), 'admin', 'aceptada' FROM usuarios
        ON CONFLICT DO NOTHING
    ''')

    # 3. Asignar casa activa
    op.execute("UPDATE usuarios SET casa_activa_id = (SELECT id FROM casas ORDER BY id ASC LIMIT 1) WHERE casa_activa_id IS NULL")

    # 4. Actualizar todos los casa_id en las tablas
    tables = [
        'comercios', 'configuracion_global', 'detalle_gastos', 'division_gastos', 
        'eventos_logisticos', 'gastos', 'historial_tareas', 'horario_comidas', 
        'ingrediente_receta', 'menu_semanal', 'metas_ahorro', 'modelo_tareas', 
        'movimientos', 'productos', 'recetas', 'salas', 'salto_tareas', 
        'sub_ubicaciones', 'suscripciones_deporte', 'tareas', 'ubicaciones'
    ]
    for table in tables:
        op.execute(f"UPDATE {table} SET casa_id = (SELECT id FROM casas ORDER BY id ASC LIMIT 1) WHERE casa_id IS NULL")
        # Hacer la columna NOT NULL
        op.execute(f"ALTER TABLE {table} ALTER COLUMN casa_id SET NOT NULL")

    # 5. Aplicar RLS a todas menos eventos_logisticos
    for table in tables:
        if table != 'eventos_logisticos':
            op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
            op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY;")
            op.execute(f"CREATE POLICY aislar_casa ON {table} USING (casa_id = NULLIF(current_setting('app.current_casa_id', TRUE), '')::integer);")
    
    # --- End Custom Migration ---

    # ### end Alembic commands ###
