"""Modulos_Menus_Horarios

Revision ID: c9d97714ae0b
Revises: 3ad7345092a4
Create Date: 2026-07-20 22:59:25.301466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d97714ae0b'
down_revision = '3ad7345092a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingrediente_receta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad_requerida', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingrediente_receta', schema=None) as batch_op:
        batch_op.drop_column('cantidad_requerida')

    # ### end Alembic commands ###
