"""init_docker_schema

Revision ID: e5af5afc29b7
Revises: 
Create Date: 2026-08-26 20:00:35.455216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5af5afc29b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('codigo_invitacion', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('casas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_casas_codigo_invitacion'), ['codigo_invitacion'], unique=True)

    op.create_table('comercios',
    sa.Column('casa_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['casa_id'], ['casas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracion_global',
    sa.Column('casa_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_principal_telegram_id', sa.String(length=50), nullable=True),
    sa.Column('hora_alerta_stock', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['casa_id'], ['casas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horario_comidas',
    sa.Column('casa_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_comida', sa.String(length=50), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['casa_id'], ['casas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mascotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('casa_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('especie', sa.String(length=50), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['casa_id'], ['casas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metas_ahorro',
    sa.Column('casa_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('monto_objetivo', sa.Float(), nullable=False),
    sa.Column('monto_actual', sa.Float(), nullable=True),
    sa.Column('fecha_limite', sa.Date(), nullable=True),
    sa.Column('icono', sa.String(length=50), nullable=True),
    sa.Column('completada', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['casa_id'], ['casas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modelo_tareas',
    sa.Column('casa_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('prioridad', sa.String(length=50), nullable=True),
    sa.Column('tipo_frecuencia', sa.String(length=50), nullable=True),
    sa.Column('valor_frecuencia', sa.String(length=50), nullable=True),
    sa.Column('alternar', sa.Boolean(), nullable=True),
    sa.Column('fecha_ultima_ejecucion', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['casa_id'], ['casas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recetas',
    sa.Column('casa_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('es_rapida', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['casa_id'], ['casas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salas',
    sa.Column('casa_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('piso', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['casa_id'], ['casas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=50), nullable=True),
    sa.Column('telegram_link_token', sa.String(length=10), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_tablet', sa.Boolean(), nullable=True),
    sa.Column('casa_activa_id', sa.Integer(), nullable=True),
    sa.Column('recibir_resumen_matutino', sa.Boolean(), nullable=True),
    sa.Column('recibir_alertas_vencimiento', sa.Boolean(), nullable=True),
    sa.Column('recibir_recordatorios_tareas', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['casa_activa_id'], ['casas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_chat_id'),
    sa.UniqueConstraint('telegram_link_token'),
    sa.UniqueConstraint('username')
    )
    op.create_table('eventos_logisticos',
    sa.Column('casa_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('creador_id', sa.Integer(), nullable=False),
    sa.Column('asignado_id', sa.Integer(), nullable=True),
    sa.Column('frecuencia', sa.String(length=20), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['asignado_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['casa_id'], ['casas.id'], ),
    sa.ForeignKeyConstraint(['creador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gastos',
    sa.Column('casa_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('imagen_ticket_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['casa_id'], ['casas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_semanal',
    sa.Column('casa_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.String(length=20), nullable=False),
    sa.Column('tipo_comida', sa.String(length=50), nullable=False),
    sa.Column('receta_id', sa.Integer(), nullable=False),
    sa.Column('fecha_asignada', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['casa_id'], ['casas.id'], ),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suscripciones_deporte',
    sa.Column('casa_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('external_api_id', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['casa_id'], ['casas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tareas',
    sa.Column('casa_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('prioridad', sa.String(length=50), nullable=True),
    sa.Column('tipo_frecuencia', sa.String(length=50), nullable=True),
    sa.Column('valor_frecuencia', sa.String(length=50), nullable=True),
    sa.Column('fecha_ultima_ejecucion', sa.Date(), nullable=True),
    sa.Column('fecha_programada', sa.Date(), nullable=True),
    sa.Column('alternar', sa.Boolean(), nullable=True),
    sa.Column('completada', sa.Boolean(), nullable=True),
    sa.Column('modelo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['casa_id'], ['casas.id'], ),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelo_tareas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ubicaciones',
    sa.Column('casa_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('sala_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['casa_id'], ['casas.id'], ),
    sa.ForeignKeyConstraint(['sala_id'], ['salas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_casa',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('casa_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=True),
    sa.Column('estado_invitacion', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['casa_id'], ['casas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'casa_id')
    )
    op.create_table('usuario_modelo_tarea',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('modelo_tarea_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['modelo_tarea_id'], ['modelo_tareas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'modelo_tarea_id')
    )
    op.create_table('detalle_gastos',
    sa.Column('casa_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gasto_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['casa_id'], ['casas.id'], ),
    sa.ForeignKeyConstraint(['gasto_id'], ['gastos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('division_gastos',
    sa.Column('casa_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gasto_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('monto_adeudado', sa.Float(), nullable=False),
    sa.Column('esta_pagado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['casa_id'], ['casas.id'], ),
    sa.ForeignKeyConstraint(['gasto_id'], ['gastos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial_tareas',
    sa.Column('casa_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tarea_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['casa_id'], ['casas.id'], ),
    sa.ForeignKeyConstraint(['tarea_id'], ['tareas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salto_tareas',
    sa.Column('casa_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tarea_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('motivo', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['casa_id'], ['casas.id'], ),
    sa.ForeignKeyConstraint(['tarea_id'], ['tareas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_ubicaciones',
    sa.Column('casa_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ubicacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['casa_id'], ['casas.id'], ),
    sa.ForeignKeyConstraint(['ubicacion_id'], ['ubicaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_tarea',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tarea_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tarea_id'], ['tareas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'tarea_id')
    )
    op.create_table('productos',
    sa.Column('casa_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('stock_actual', sa.Float(), nullable=True),
    sa.Column('stock_minimo', sa.Float(), nullable=True),
    sa.Column('unidad_medida', sa.String(length=20), nullable=True),
    sa.Column('en_lista', sa.Boolean(), nullable=True),
    sa.Column('es_temporal', sa.Boolean(), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('fecha_ultima_compra', sa.Date(), nullable=True),
    sa.Column('ubicacion_id', sa.Integer(), nullable=True),
    sa.Column('sub_ubicacion_id', sa.Integer(), nullable=True),
    sa.Column('comercio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['casa_id'], ['casas.id'], ),
    sa.ForeignKeyConstraint(['comercio_id'], ['comercios.id'], ),
    sa.ForeignKeyConstraint(['sub_ubicacion_id'], ['sub_ubicaciones.id'], ),
    sa.ForeignKeyConstraint(['ubicacion_id'], ['ubicaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingrediente_receta',
    sa.Column('casa_id', sa.Integer(), nullable=True),
    sa.Column('receta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_requerida', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['casa_id'], ['casas.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id'], ),
    sa.PrimaryKeyConstraint('receta_id', 'producto_id')
    )
    op.create_table('movimientos',
    sa.Column('casa_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['casa_id'], ['casas.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # --- INYECCIÓN MANUAL DE RLS ---
    op.execute('ALTER TABLE productos ENABLE ROW LEVEL SECURITY;')
    op.execute('ALTER TABLE productos FORCE ROW LEVEL SECURITY;')
    op.execute("CREATE POLICY aislar_casa ON productos USING (casa_id = NULLIF(current_setting('app.current_casa_id', TRUE), '')::integer);")
    
    op.execute('ALTER TABLE gastos ENABLE ROW LEVEL SECURITY;')
    op.execute('ALTER TABLE gastos FORCE ROW LEVEL SECURITY;')
    op.execute("CREATE POLICY aislar_casa ON gastos USING (casa_id = NULLIF(current_setting('app.current_casa_id', TRUE), '')::integer);")
    
    op.execute('ALTER TABLE tareas ENABLE ROW LEVEL SECURITY;')
    op.execute('ALTER TABLE tareas FORCE ROW LEVEL SECURITY;')
    op.execute("CREATE POLICY aislar_casa ON tareas USING (casa_id = NULLIF(current_setting('app.current_casa_id', TRUE), '')::integer);")
    
    op.execute('ALTER TABLE mascotas ENABLE ROW LEVEL SECURITY;')
    op.execute('ALTER TABLE mascotas FORCE ROW LEVEL SECURITY;')
    op.execute("CREATE POLICY aislar_casa ON mascotas USING (casa_id = NULLIF(current_setting('app.current_casa_id', TRUE), '')::integer);")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimientos')
    op.drop_table('ingrediente_receta')
    op.drop_table('productos')
    op.drop_table('usuario_tarea')
    op.drop_table('sub_ubicaciones')
    op.drop_table('salto_tareas')
    op.drop_table('historial_tareas')
    op.drop_table('division_gastos')
    op.drop_table('detalle_gastos')
    op.drop_table('usuario_modelo_tarea')
    op.drop_table('usuario_casa')
    op.drop_table('ubicaciones')
    op.drop_table('tareas')
    op.drop_table('suscripciones_deporte')
    op.drop_table('menu_semanal')
    op.drop_table('gastos')
    op.drop_table('eventos_logisticos')
    op.drop_table('usuarios')
    op.drop_table('salas')
    op.drop_table('recetas')
    op.drop_table('modelo_tareas')
    op.drop_table('metas_ahorro')
    op.drop_table('mascotas')
    op.drop_table('horario_comidas')
    op.drop_table('configuracion_global')
    op.drop_table('comercios')
    with op.batch_alter_table('casas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_casas_codigo_invitacion'))

    op.drop_table('casas')
    # ### end Alembic commands ###
